extern int cloud_providers_account_get_status() { return 0; }
extern void *cloud_providers_account_get_action_group() { return 0; }
extern void *cloud_providers_account_get_icon() { return 0; }
extern void *cloud_providers_account_get_menu_model() { return 0; }
extern void *cloud_providers_account_get_name() { return 0; }
extern void *cloud_providers_account_get_path() { return 0; }
extern void *cloud_providers_account_get_status_details() { return 0; }
extern void *cloud_providers_collector_dup_singleton() { return 0; }
extern void *cloud_providers_collector_get_providers() { return 0; }
extern void *cloud_providers_provider_get_accounts() { return 0; }
